version: '3.4'
services:

  nginx:
    image: nginx
    ports:
      - '80:80'
      - '7878:7878'
      - '8989:8989'
      - '9117:9117'
    networks:
      - default
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/htpasswd:/htpasswd'

  openvpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: EST5EDT
    networks:
      - default
    dns:
      - 209.222.18.222
      - 209.222.18.218
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - 'label:disable'
    stdin_open: true
    tty: true
    volumes:
      - '/dev/net:/dev/net:z'
      - './openvpn:/vpn:ro'

  rutorrent:
    image: linuxserver/rutorrent
    depends_on:
      - openvpn
    environment:
      TZ: America/New_York
      PGID: 1000
      PUID: 1000
    network_mode: 'service:openvpn'
    volumes:
      - './rutorrent/config:/config'
      - './rutorrent/downloads:/downloads'

  jackett:
    image: linuxserver/jackett
    depends_on:
      - openvpn
    environment:
      TZ: America/New_York
      PGID: 1000
      PUID: 1000
    network_mode: 'service:openvpn'
    volumes:
      - './jackett/config:/config'
      - './jackett/downloads:/downloads'

  radarr:
    image: linuxserver/radarr
    depends_on:
      - openvpn
    environment:
      TZ: America/New_York
      PGID: 1000
      PUID: 1000
    network_mode: 'service:openvpn'
    volumes:
      - './radarr/config:/config'
      - './radarr/downloads:/downloads'
      - './radarr/movies:/movies'

  sonarr:
    image: linuxserver/sonarr
    depends_on:
      - openvpn
    environment:
      TZ: America/New_York
      PGID: 1000
      PUID: 1000
    network_mode: 'service:openvpn'
    volumes:
      - './sonarr/config:/config'
      - './sonarr/downloads:/downloads'
      - './sonarr/tv:/tv'

networks:
  default:
