version: '3.4'
services:

  nginx:
    image: nginx
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    environment:
      HTTP_USER: ${HTTP_USER}
      HTTP_PASSWORD: ${HTTP_PASSWORD}
    depends_on:
      - rutorrent
      - jackett
      - radarr
      - sonarr
    ports:
      - 80:80
      - 7878:7878
      - 8989:8989
      - 9117:9117
    networks:
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always

  openvpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    environment:
      TZ: ${TZ}
    networks:
      - default
    dns:
      - 209.222.18.222
      - 209.222.18.218
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ./openvpn:/vpn:ro
    restart: always

  rutorrent:
    image: linuxserver/rutorrent
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${RUTORRENT_CONFIG}:/config
      - ${RUTORRENT_DOWNLOADS_COMPLETE}:/downloads/completed
      - ${RUTORRENT_DOWNLOADS_INCOMPLETE}:/downloads/incoming
      - ${RUTORRENT_DOWNLOADS_WATCH}:/downloads/watched
    restart: always

  jackett:
    image: linuxserver/jackett
    depends_on:
      - openvpn
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${JACKETT_CONFIG}:/config
      - ${JACKETT_DOWNLOADS}:/downloads
    restart: always

  radarr:
    image: radarr
    build:
      context: ./dockerfiles
      dockerfile: radarr.dockerfile
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${RADARR_DOWNLOADS}:/downloads
      - ${RADARR_MOVIES}:/movies
    restart: always

  sonarr:
    image: sonarr
    build:
      context: ./dockerfiles
      dockerfile: sonarr.dockerfile
    depends_on:
      - rutorrent
      - jackett
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    network_mode: service:openvpn
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${SONARR_DOWNLOADS}:/downloads
      - ${SONARR_TV}:/tv
    restart: always

networks:
  default:
